version: "2"
services:
#  springboot:
#    build: .
#    restart: always
#    container_name: springboot
#    ports:
#      - 8182:8080
#    working_dir: /opt/app
#    depends_on:
#      - mongo
  mongo:
    restart: always
    image: mongo:4.0.1
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_NON_ROOT_USERNAME="user"
      - MONGO_NON_ROOT_PASSWORD="pass"
      - MONGO_INITDB_DATABASE="shopping-cart"
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/var/micro-data/mongodb/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet