server:
  port: 8080
  servlet:
    context-path: /api/shopping-cart-service

logging:
  level:
    ro.processor: DEBUG
    org.springframework: WARN
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

application:
  shopping-cart-service:
    name: shopping-cart-service
  config:
    mongo:
      database: shopping-cart
      host: mongodb://localhost:27017/shopping-cart
